!new:anonymization.modules.speaker_embeddings.anonymization.pool_anon.PoolAnonymizer
  data_dir: !PLACEHOLDER # to be overridden by the main config
  embed_model_path: !PLACEHOLDER # to be overridden by the main config
  pool_data_dir: !ref <data_dir>/libritts_train_other_500
  pool_vec_path: !ref <vectors_dir>/style-embed_spk-level/pool_embeddings
  N: 200
  N_star: 100
  distance: plda    # possible: plda, cosine
  plda_dir: !ref <models_dir>/distances/plda/libritts_train_other_500_xvector
  cross_gender: false
  proximity: farthest    # possible: farthest, nearest, center
  scaling: maxmin    # possible: none, maxmin, mean
  stats_per_dim_path: !ref <models_dir>/anonymization/stats_per_dim.json