root_dir : ..
data_dir: !ref data  # TODO adjust path
save_output: true

datasets:
  - name: libri_dev
    data: libri
    set: dev
    enrolls: [enrolls]
    trials: [trials_f, trials_m]
  - name: libri_test
    data: libri
    set: test
    enrolls: [enrolls]
    trials: [trials_f, trials_m]
  - name: vctk_dev
    data: vctk
    set: dev
    enrolls: [enrolls]
    trials: [trials_f_all, trials_m_all]
  - name: vctk_test
    data: vctk
    set: test
    enrolls: [enrolls]
    trials: [trials_f_all, trials_m_all]


dataset_libri_360: !ref <data_dir>/train-clean-360-asv
results_dir: !ref results # TODO adjust path
pipeline: dsp

modules:
  anon_suffix: _dsp
  n_coeffs: 20
  mc_coeff_min: 0.5
  mc_coeff_max: 0.9
  winLengthinms: 20
  shiftLengthinms: 10
  seed: 0
  anon_level: spk
  anon_level_libri_360: utt
