root_dir : ..
data_dir: data
results_dir: exp/dsp_anon # TODO adjust path
save_output: true

datasets:
  - name: libri_dev
    data: libri
    set: dev
    enrolls: [enrolls]
    trials: [trials_f, trials_m]
  - name: libri_test
    data: libri
    set: test
    enrolls: [enrolls]
    trials: [trials_f, trials_m]


dataset_libri_360: !ref <data_dir>/train-clean-360
pipeline: dsp

modules:
  anon_suffix: _dsp
  n_coeffs: 20
  mc_coeff_min: 0.5
  mc_coeff_max: 0.9
  winLengthinms: 20
  shiftLengthinms: 10
  seed: 0
  anon_level: spk
  anon_level_libri_360: utt
