root_dir: .
exp_dir: !ref <root_dir>/exp
anon_data_dir: !PLACEHOLDER # TODO path to anonymized data (raw audios), e.g. <anon_data_dir>/libri_test_enrolls/*wav etc.
data_dir: data
results_summary_dir: !ref <exp_dir>/results_summary/eval_pre

datasets:
  - name: libri_dev
    data: libri
    set: dev
    enrolls: [enrolls]
    trials: [trials_f, trials_m]
  - name: libri_test
    data: libri
    set: test
    enrolls: [enrolls]
    trials: [trials_f, trials_m]
  - name: vctk_dev
    data: vctk
    set: dev
    enrolls: [enrolls]
    trials: [trials_f_all, trials_m_all]
  - name: vctk_test
    data: vctk
    set: test
    enrolls: [enrolls]
    trials: [trials_f_all, trials_m_all]


eval_steps:  # all metrics in this list will be computed in the evaluation. Remove entry to skip
  privacy:
    - asv
  utility:
    - asr
    - gvd

anon_data_suffix: b1  # suffix for dataset to signal that it is anonymized
eval_data_dir: data  # path to anonymized evaluation data in kaldi format, e.g. <eval_data_dir>/libri_test_enrolls/wav.scp etc.

privacy:
  asv:
    model_dir: !ref <exp_dir>/asv_pre_<privacy[asv][vec_type]>  # path to existing ASV model or output for trained ASV model
    vec_type: ecapa  # ecapa or xvector
    evaluation:
      results_dir: !ref <privacy[asv][model_dir]>  # path to save evaluation results
      distance: cosine  # cosine or plda
      plda:   # ignored if distance is not plda
        model_dir: null  # path to trained PLDA or output of PLDA training
        train_data_dir: null # path to PLDA training data
        anon: null # trained on anonymized (true) or original (false) data

utility:
  asr:
    backend: speechbrain
    model_name: asr_pre_sb  # name for ASR model
    
    evaluation:
      model_dir: !ref <exp_dir>/<utility[asr][model_name]>
      eval_batchsize: 2 # eval_batchsize(32g)=3 ->9h eval_batchsize=2->12h eval_batchsize(12GB)=1->24h
      results_dir: !ref <exp_dir>/<utility[asr][model_name]>


  gvd:
    num_utt: all  # all or specific number, number of utterances per speaker
    asv_params:  # settings for ASV using for GVD evaluation
      model_dir: !ref <privacy[asv][model_dir]>
      vec_type: !ref <privacy[asv][vec_type]>
      evaluation:
        plda: !ref <privacy[asv][evaluation][plda]>
        distance: !ref <privacy[asv][evaluation][distance]>
    results_dir: !ref <privacy[asv][model_dir]>  # path to results dir for GVD computation
    recompute: false  # recompute similarity matrices in any case (true) or skip if matrices exist (false)
