root_dir: .
exp_dir: !ref <root_dir>/exp
#anon_data_dir: !PLACEHOLDER # TODO path to anonymized data (raw audios), e.g. <anon_data_dir>/libri_test_enrolls/*wav etc.
anon_data_dir: exp/dsp_anon
#anon_data_suffix: !PLACEHOLDER  # TODO suffix for dataset to signal that it is anonymized e.g. dsp, b1b, gan
anon_data_suffix: dsp
data_dir: data
results_summary_dir: !ref <exp_dir>/results_summary/eval_pre

datasets:
  - name: libri_dev
    data: libri
    set: dev
    enrolls: [enrolls]
    trials: [trials_f, trials_m]
  - name: libri_test
    data: libri
    set: test
    enrolls: [enrolls]
    trials: [trials_f, trials_m]


eval_steps:  # all metrics in this list will be computed in the evaluation. Remove entry to skip
  privacy:
    - asv
  utility:
    - asr

eval_data_dir: data  # path to anonymized evaluation data in kaldi format, e.g. <eval_data_dir>/libri_test_enrolls/wav.scp etc.

privacy:
  asv:
    model_dir: !ref <exp_dir>/asv_pre_<privacy[asv][vec_type]>  # path to existing ASV model or output for trained ASV model
    vec_type: ecapa  # ecapa or xvector
    evaluation:
      results_dir: !ref <privacy[asv][model_dir]>  # path to save evaluation results
      distance: cosine  # cosine or plda
      plda:   # ignored if distance is not plda
        model_dir: null  # path to trained PLDA or output of PLDA training
        train_data_dir: null # path to PLDA training data
        anon: null # trained on anonymized (true) or original (false) data

utility:
  asr:
    backend: speechbrain
    model_name: asr_pre_sb  # name for ASR model
    
    evaluation:
      model_dir: !ref <exp_dir>/<utility[asr][model_name]>
      eval_batchsize: 2 # eval_batchsize(32g)=3 ->9h eval_batchsize=2->12h eval_batchsize(12GB)=1->24h
      results_dir: !ref <exp_dir>/<utility[asr][model_name]>


